#
# More configuration examples at:
# http://jekyllrb.com/docs/configuration/
#

#
# Jekyll basic configurations
#

<<<<<<< HEAD
source:         _app
destination:    _site
timezone:       Asia/Hong_Kong
permalink:      /:categories/:title/
markdown:       kramdown
highlighter:    rouge
include:        ["_pages"]
exclude:        ["_pages/themes"]
=======
source:         ./_app
destination:    ./_site
timezone:       America/Los_Angeles
permalink:      /
markdown:       kramdown
highlighter:    rouge
include:        ["_pages"]exclude:        ["_pages/themes"]
>>>>>>> 76b04d79202718c33ec951b2e75372359ba32954

#
# Jekyll serve settings
#

port:           4321

#
# Jekyll build settings
#

future:         false

#
<<<<<<< HEAD
# Markdown settings
#

=======
# Additional Markdown settings
#
>>>>>>> 76b04d79202718c33ec951b2e75372359ba32954
kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  syntax_highlighter_opts:
    css_class:               "highlight"
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"

<<<<<<< HEAD
=======
# redcarpet:
#   extensions:
#     - footnotes
#     - no_intra_emphasis
#     - smart
#     - space_after_headers
#     - superscript
#     - tables

>>>>>>> 76b04d79202718c33ec951b2e75372359ba32954
#
# Jekyll plugins
#

plugins:
  - jekyll-last-modified-at
  - match_regex

#
<<<<<<< HEAD
# Almace Scaffolding settings
#

# Development mode
#
# Development mode is disabled on production build by default, we've enabled it
# in `_config.dev.yml` for local development, so most of the time you don't
# need to change it.
#
# Default:      false
dev:            false

# Site name
#
# Default:      Almace Scaffolding
name:           Sparanoid

# Site short name
#
# Currently only used by Chrome Web App manifest, can be anything you like.
# You can also just use your `name` for `name_short` if it is short enough
#
# For example:
# - name:       Almace Scaffolding
# - name_short: AMSF
#
# or:
# - name:       Sparanoid Group
# - name_short: Sparanoid
#
# Default:      AMSF
name_short:     Sparanoid

# Site description
#
# Will be used in the document meta and Atom feed subtitle
#
# Default:      Almace Scaffolding - Super-fast Jekyll framework
description:    I make things that don’t suck.

# Base URL
#
# This is useful when I need to build site in a subdirectory (like
# GitHub Pages for Projects), it provides a specific URL prefix, for example, if
# the production site URL is https://sparanoid.com/my-project/, set `baseurl` to
# `/my-project`, without trailing slash.
#
# Default:      ""
baseurl:        ""

# CSS path used in templates
#
# Default:      /assets
assets:         /assets

# Feed URL
#
# Define your main feed URL, this will be only used in your templates
#
# Default:      /feed.xml
feed:           /feed.xml

# Site full URL
#
# Used in atom feed, sitemap, Twitter Cards, and etc. I should use absolute full
# URLs for these fields
#
# Default:      https://sparanoid.com
url:            https://sparanoid.com

# Media assets URL
#
# Media assets URL are used in posts, without trailing slash. ie.
# `<img src="{{ site.file }}/image.png">`. In the most cases this URL should be
# powered by a CDN provider
# Note: you should avoid protocol-free (ie. //cdn.mysite.tld) address here
# because Twitter Cards doesn't work well with protocol-free assets when AMSF
# grabs the first image of your post as post featured image.
#
# Default:      https://d349cztnlupsuf.cloudfront.net
file:           https://d349cztnlupsuf.cloudfront.net

# Download files URL
#
# Download files URL are used in posts, ie.
# href="{{ site.download }}/package.zip", this should also be a CDN link just
# like `site.file`. There're no notable differences in `site.file` and
# `site.download`, I just use the one for post images and the other for large
# download files. That's it. Remove or ignore this if you don't need it.
#
# Default:      https://d1bmx7s6749k4k.cloudfront.net
download:       https://d1bmx7s6749k4k.cloudfront.net
=======
# User defined settings
#

# Site name
name:           Ge Yubiquity.

# Site description, will appear in the document meta and Atom feed subtitle
description:    Visual Art And Interactive Design.

# Site short name
name_short:     GY

# Base URL, this is useful when I need to build site in a sub-directory (like GitHub Pages for Projects), it provides a specific URL prefix, for example, if the production site URL is http://sparanoid.com/lab/version/, set `base` to `/lab/version/24`, without trailing slash.
# Default:      null
base:           null

# CSS path used in templates
# Default:      /assets
assets:         /assets

# Since I use `/feed/index.xml` as feed permalink, `{{ page.url }}` won't pass feed validation with "Self reference doesn't match document location" error
# Default:      /feed
feed:           /feed

# Used in atom feed, sitemap, Twitter Cards, and etc. I should use absolute full URLs for these fields
url:            http://www.geyu.me

# Media assets URL used in posts, without trailing slash. ie. `<img href="{{ site.file }}/image.png">`. In the most cases this URL should be powered by a CDN provider
file:           http://rsrc.geyu.me

# Download files URL used in posts, ie. href="{{ site.download }}/package.zip", this should also be a CDN link just like `site.url`. There's no differences in `site.url` and `site.download`, I just use one CDN for post images and another for large download files. That's it. Remove or ignore this if you don't need it
download:       http://dl.geyu.me
>>>>>>> 76b04d79202718c33ec951b2e75372359ba32954

# Colors
#
# Used by Safari mask-icon, Chrome Web App theme color
colors:
  theme:        "#a212d1"
  background:   "#fff"

# Service Worker Precache
service_worker:
  enabled:      true
  max_size:     120000
  files:
    - "**/*.{css,html,jpg,gif,png,svg,woff,woff2}"
    - "**/js/**.js"

# Google Analytics tracking code
google_analytics:
  enabled:      false
  id:           UA-xxxxxxx
  url:          https://www.googletagmanager.com/gtag/js

<<<<<<< HEAD
# Site Twitter account handle
twitter:        sparanoid

# Twitter Cards large images
#
# Use summary card with large image for Twitter Cards, require theme support
#
# Default:      true
tc_large_image: true

# Force UTF-8 encoding
#
# Enable this will simply add <meta charset="utf-8"> to the head of your pages
#
# Default:      false
force_utf_8:    false

# Link blog
#
# Enable this settings to make your feed Daring Fireball-like link blog (This
# basically change your <link> value to external link you defined in your posts)
#
# Default:      false
link_blog:      false

# Excerpts for RSS
#
# Change the value to true to use post excerpt for RSS feeds
#
# Default:      false
rss_excerpt:    false

# Generator credits
#
# Show or hide generator credits, require theme support
#
# Default:      true
credits:        true

# Custom records in robots.txt
#
# For example:
# robots:
#   - "User-agent: *"
#   - "Disallow: /ajax/"
#   - "Disallow: /@async"
#   - "Disallow: /log/"
#
# Default:      "User-agent: *"
robots:
  - "User-agent: *"
  - "Disallow: /lab/version/"
=======
# User related information
# {{ site.profile.user }}: author name, used in post pages, and atom feed
# {{ site.profile.email }}: used in atom feed, homepage, and about page
# {{ site.profile.twitter.creator }}: used by Twitter Cards
# {{ site.profile.twitter.site }}: used by Twitter Cards
# {{ site.profile.google_plus }}: used in footer, this link is display: noned, only to pass Google+ authorship check
# {{ site.profile.donate }}: a donate link used in posts like `<a href="{{ site.profile.donate }}">Donate me</a>`
profile:
  user:         Ge Yu
  email:        geyubiquity@gmail.com
  twitter:
    creator:    geyu
    site:       yubiquity
  google_plus:  geyubiquity
  donate:       null

# Enable this settings to make your feed Daring Fireball-like link blog
# (This basically change your <link> value to external link you defined in your posts)
# Default:      false
link_blog:      false

# Change the value to true to use post excerpt for RSS feeds
# Default:      false
rss_excerpt:    false

# Hide footer from your homepage, example: sparanoid.com
# Default:      false
clean_homepage: false

# Style post link color (if defined) for article list
# Default:      false
colorful_list:  false

# Show generator credits
# Default:      true
credits:        true

#
# Custom distribution variables
#

# SSH remote server hostname
remote_host:    caladbolg

# Prevent them from being deleted on server (rsync --delete), these files and directories are available on the remote server but outside this git repo. I need to ignore them.
ignore_files:   #--exclude=lab

# Media assets sync'ed using s3cmd
static_files:   ~/gyuchinese.github.io

# Remote server root directory
remote_dir:     #/srv/www/sparanoid.com/public_html

# Amazon S3 Bucket variable for s3cmd
s3_bucket:      #s3://sparanoid/
>>>>>>> 76b04d79202718c33ec951b2e75372359ba32954
